console.log('||||||||||||||||||||||||||||||||||||||');
console.log('EXAMPLE_REMOTE_HOST: ', process.env.EXAMPLE_REMOTE_HOST);
console.log('EXAMPLE_REMOTE_USER: ', process.env.EXAMPLE_REMOTE_USER);
console.log('EXAMPLE_SSH_PRIVATE_KEY: ', process.env.EXAMPLE_SSH_PRIVATE_KEY);
console.log('||||||||||||||||||||||||||||||||||||||');
console.log('EXAMPLE_REMOTE_HOST1: ', process.env.EXAMPLE_REMOTE_HOST1);
console.log('EXAMPLE_REMOTE_USER1: ', process.env.EXAMPLE_REMOTE_USER1);
console.log('EXAMPLE_SSH_PRIVATE_KEY1: ', process.env.EXAMPLE_SSH_PRIVATE_KEY1);
console.log('||||||||||||||||||||||||||||||||||||||');
console.log('REMOTE_USER: ', process.env.REMOTE_USER);
console.log('REMOTE_HOST: ', process.env.REMOTE_HOST);
console.log('SSH_PRIVATE_KEY: ', process.env.SSH_PRIVATE_KEY);
console.log('||||||||||||||||||||||||||||||||||||||');
